### ISSUE TITLE
存在逻辑bug

### ISSUE THREAD

**Issue by daofeng2015** [xbugio/aliyundrive#1]
```
if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
		return "", err
	}
```
如果阿里云的api返回的resp里面没有body,就会报错,应该先判断返回状态码再做json处理,还有能把文件打开和文件夹上传也支持了?

**Comment by xbugio** [comment]
> ```
> if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> 		return "", err
> 	}
> ```
> 
> 
>      
>   
> 
> 如果阿里云的api返回的resp里面没有body,就会报错,应该先判断返回状态码再做json处理,还有能把文件打开和文件夹上传也支持了?

resp.Body如果有问题，Decode也会返回err，就没有细分err的类型了，感觉是无伤大雅哈哈。
文件夹上传的话，对文件夹做个递归遍历，再实现一下阿里云盘的文件夹创建操作 ，就可以了。
文件打开，在我另外一个项目上做了，因为阿里云盘对资源做了referer头的防盗链检查，所以需要加上这个referer头。
这个项目后续想做成webdav形式的，近期在搞teambition网盘的，那个没有做referer头限制，所以近期都会在更新teambition的网盘。这个后续再更新。

**Comment by daofeng2015** [comment]
> > ```
> > if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> > 		return "", err
> > 	}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果阿里云的api返回的resp里面没有body,就会报错,应该先判断返回状态码再做json处理,还有能把文件打开和文件夹上传也支持了?
> 
> resp.Body如果有问题，Decode也会返回err，就没有细分err的类型了，感觉是无伤大雅哈哈。
> 文件夹上传的话，对文件夹做个递归遍历，再实现一下阿里云盘的文件夹创建操作 ，就可以了。
> 文件打开，在我另外一个项目上做了，因为阿里云盘对资源做了referer头的防盗链检查，所以需要加上这个referer头。
> 这个项目后续想做成webdav形式的，近期在搞teambition网盘的，那个没有做referer头限制，所以近期都会在更新teambition的网盘。这个后续再更新。

我是在做上传测试的过程发现的,通过```
body := strings.NewReader(`{"refresh_token":"` + d.RefreshToken + `"}`)
	request, err := http.NewRequestWithContext(ctx, "POST", ApiRefreshToken, body)
	if err != nil {
		return "", err
	}
	setRequestHeader(request.Header)
	request.Header.Set("content-type", "application/json;charset=UTF-8")
	request.Header.Set("accept", "application/json, text/plain, */*")

	resp, err := d.httpClient.Do(request)
	if resp != nil && resp.Body != nil {
		defer resp.Body.Close()
	}
	if err != nil {
		return "", err
	}

	ret := &struct {
		AccessToken    string `json:"access_token"`
		ExpiresIn      int64  `json:"expires_in"`
		DefaultDriveID string `json:"default_drive_id"`
		RefreshToken   string `json:"refresh_token"`
	}{}

	if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
		return "", err
	}
```
这里发现的，如果失败就直接```
2021/06/28 23:47:52 错误:invalid character '<' looking for beginning of value
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x290b58]
```
报错的

**Comment by xbugio** [comment]
> > > ```
> > > if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> > > 		return "", err
> > > 	}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 如果阿里云的api返回的resp里面没有body,就会报错,应该先判断返回状态码再做json处理,还有能把文件打开和文件夹上传也支持了?
> > 
> > 
> > resp.Body如果有问题，Decode也会返回err，就没有细分err的类型了，感觉是无伤大雅哈哈。
> > 文件夹上传的话，对文件夹做个递归遍历，再实现一下阿里云盘的文件夹创建操作 ，就可以了。
> > 文件打开，在我另外一个项目上做了，因为阿里云盘对资源做了referer头的防盗链检查，所以需要加上这个referer头。
> > 这个项目后续想做成webdav形式的，近期在搞teambition网盘的，那个没有做referer头限制，所以近期都会在更新teambition的网盘。这个后续再更新。
> 
> 
> 我是在做上传测试的过程发现的,通过
> 
> 
> ```
> body := strings.NewReader(`{"refresh_token":"` + d.RefreshToken + `"}`)
> 	request, err := http.NewRequestWithContext(ctx, "POST", ApiRefreshToken, body)
> 	if err != nil {
> 		return "", err
> 	}
> 	setRequestHeader(request.Header)
> 	request.Header.Set("content-type", "application/json;charset=UTF-8")
> 	request.Header.Set("accept", "application/json, text/plain, */*")
> 
> 	resp, err := d.httpClient.Do(request)
> 	if resp != nil && resp.Body != nil {
> 		defer resp.Body.Close()
> 	}
> 	if err != nil {
> 		return "", err
> 	}
> 
> 	ret := &struct {
> 		AccessToken    string `json:"access_token"`
> 		ExpiresIn      int64  `json:"expires_in"`
> 		DefaultDriveID string `json:"default_drive_id"`
> 		RefreshToken   string `json:"refresh_token"`
> 	}{}
> 
> 	if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> 		return "", err
> 	}
> ```
> 
> 
>      
>   
> 
> 这里发现的，如果失败就直接
> 
> 
> ```
> 2021/06/28 23:47:52 错误:invalid character '<' looking for beginning of value
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x28 pc=0x290b58]
> ```
> 
> 
>      
>   
> 
> 报错的

原来如此，没有注意到如果resp.Body为空，NewDecoder会返回nil，感谢反馈。

**Comment by daofeng2015** [comment]
> > > > ```
> > > > if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> > > > 		return "", err
> > > > 	}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 如果阿里云的api返回的resp里面没有body,就会报错,应该先判断返回状态码再做json处理,还有能把文件打开和文件夹上传也支持了?
> > > 
> > > 
> > > resp.Body如果有问题，Decode也会返回err，就没有细分err的类型了，感觉是无伤大雅哈哈。
> > > 文件夹上传的话，对文件夹做个递归遍历，再实现一下阿里云盘的文件夹创建操作 ，就可以了。
> > > 文件打开，在我另外一个项目上做了，因为阿里云盘对资源做了referer头的防盗链检查，所以需要加上这个referer头。
> > > 这个项目后续想做成webdav形式的，近期在搞teambition网盘的，那个没有做referer头限制，所以近期都会在更新teambition的网盘。这个后续再更新。
> > 
> > 
> > 我是在做上传测试的过程发现的,通过
> > ```
> > body := strings.NewReader(`{"refresh_token":"` + d.RefreshToken + `"}`)
> > 	request, err := http.NewRequestWithContext(ctx, "POST", ApiRefreshToken, body)
> > 	if err != nil {
> > 		return "", err
> > 	}
> > 	setRequestHeader(request.Header)
> > 	request.Header.Set("content-type", "application/json;charset=UTF-8")
> > 	request.Header.Set("accept", "application/json, text/plain, */*")
> > 
> > 	resp, err := d.httpClient.Do(request)
> > 	if resp != nil && resp.Body != nil {
> > 		defer resp.Body.Close()
> > 	}
> > 	if err != nil {
> > 		return "", err
> > 	}
> > 
> > 	ret := &struct {
> > 		AccessToken    string `json:"access_token"`
> > 		ExpiresIn      int64  `json:"expires_in"`
> > 		DefaultDriveID string `json:"default_drive_id"`
> > 		RefreshToken   string `json:"refresh_token"`
> > 	}{}
> > 
> > 	if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> > 		return "", err
> > 	}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这里发现的，如果失败就直接
> > ```
> > 2021/06/28 23:47:52 错误:invalid character '<' looking for beginning of value
> > panic: runtime error: invalid memory address or nil pointer dereference
> > [signal 0xc0000005 code=0x0 addr=0x28 pc=0x290b58]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 报错的
> 
> 原来如此，没有注意到如果resp.Body为空，NewDecoder会返回nil，感谢反馈。

还有一点,我说的打开时指的上传文件open,不是之down下来打开,所以这个打开操作应该也需要放到上传主方法里面

**Comment by xbugio** [comment]
> > > > > ```
> > > > > if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> > > > > 		return "", err
> > > > > 	}
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 如果阿里云的api返回的resp里面没有body,就会报错,应该先判断返回状态码再做json处理,还有能把文件打开和文件夹上传也支持了?
> > > > 
> > > > 
> > > > resp.Body如果有问题，Decode也会返回err，就没有细分err的类型了，感觉是无伤大雅哈哈。
> > > > 文件夹上传的话，对文件夹做个递归遍历，再实现一下阿里云盘的文件夹创建操作 ，就可以了。
> > > > 文件打开，在我另外一个项目上做了，因为阿里云盘对资源做了referer头的防盗链检查，所以需要加上这个referer头。
> > > > 这个项目后续想做成webdav形式的，近期在搞teambition网盘的，那个没有做referer头限制，所以近期都会在更新teambition的网盘。这个后续再更新。
> > > 
> > > 
> > > 我是在做上传测试的过程发现的,通过
> > > ```
> > > body := strings.NewReader(`{"refresh_token":"` + d.RefreshToken + `"}`)
> > > 	request, err := http.NewRequestWithContext(ctx, "POST", ApiRefreshToken, body)
> > > 	if err != nil {
> > > 		return "", err
> > > 	}
> > > 	setRequestHeader(request.Header)
> > > 	request.Header.Set("content-type", "application/json;charset=UTF-8")
> > > 	request.Header.Set("accept", "application/json, text/plain, */*")
> > > 
> > > 	resp, err := d.httpClient.Do(request)
> > > 	if resp != nil && resp.Body != nil {
> > > 		defer resp.Body.Close()
> > > 	}
> > > 	if err != nil {
> > > 		return "", err
> > > 	}
> > > 
> > > 	ret := &struct {
> > > 		AccessToken    string `json:"access_token"`
> > > 		ExpiresIn      int64  `json:"expires_in"`
> > > 		DefaultDriveID string `json:"default_drive_id"`
> > > 		RefreshToken   string `json:"refresh_token"`
> > > 	}{}
> > > 
> > > 	if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> > > 		return "", err
> > > 	}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这里发现的，如果失败就直接
> > > ```
> > > 2021/06/28 23:47:52 错误:invalid character '<' looking for beginning of value
> > > panic: runtime error: invalid memory address or nil pointer dereference
> > > [signal 0xc0000005 code=0x0 addr=0x28 pc=0x290b58]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 报错的
> > 
> > 
> > 原来如此，没有注意到如果resp.Body为空，NewDecoder会返回nil，感谢反馈。
> 
> 
> 还有一点,我说的打开时指的上传文件open,不是之down下来打开,所以这个打开操作应该也需要放到上传主方法里面

这个Open没有实现是因为上传的不一定是来自于本地磁盘上的文件，也可能是来自于web框架的一些文件，所以不一定是io.OpenFile。调用者自行Open一下也没有很繁琐，所以就没提供。可以后续考虑单独提供一个UploadFile的api

**Comment by daofeng2015** [comment]
> > > > > > ```
> > > > > > if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> > > > > > 		return "", err
> > > > > > 	}
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 如果阿里云的api返回的resp里面没有body,就会报错,应该先判断返回状态码再做json处理,还有能把文件打开和文件夹上传也支持了?
> > > > > 
> > > > > 
> > > > > resp.Body如果有问题，Decode也会返回err，就没有细分err的类型了，感觉是无伤大雅哈哈。
> > > > > 文件夹上传的话，对文件夹做个递归遍历，再实现一下阿里云盘的文件夹创建操作 ，就可以了。
> > > > > 文件打开，在我另外一个项目上做了，因为阿里云盘对资源做了referer头的防盗链检查，所以需要加上这个referer头。
> > > > > 这个项目后续想做成webdav形式的，近期在搞teambition网盘的，那个没有做referer头限制，所以近期都会在更新teambition的网盘。这个后续再更新。
> > > > 
> > > > 
> > > > 我是在做上传测试的过程发现的,通过
> > > > ```
> > > > body := strings.NewReader(`{"refresh_token":"` + d.RefreshToken + `"}`)
> > > > 	request, err := http.NewRequestWithContext(ctx, "POST", ApiRefreshToken, body)
> > > > 	if err != nil {
> > > > 		return "", err
> > > > 	}
> > > > 	setRequestHeader(request.Header)
> > > > 	request.Header.Set("content-type", "application/json;charset=UTF-8")
> > > > 	request.Header.Set("accept", "application/json, text/plain, */*")
> > > > 
> > > > 	resp, err := d.httpClient.Do(request)
> > > > 	if resp != nil && resp.Body != nil {
> > > > 		defer resp.Body.Close()
> > > > 	}
> > > > 	if err != nil {
> > > > 		return "", err
> > > > 	}
> > > > 
> > > > 	ret := &struct {
> > > > 		AccessToken    string `json:"access_token"`
> > > > 		ExpiresIn      int64  `json:"expires_in"`
> > > > 		DefaultDriveID string `json:"default_drive_id"`
> > > > 		RefreshToken   string `json:"refresh_token"`
> > > > 	}{}
> > > > 
> > > > 	if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> > > > 		return "", err
> > > > 	}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 这里发现的，如果失败就直接
> > > > ```
> > > > 2021/06/28 23:47:52 错误:invalid character '<' looking for beginning of value
> > > > panic: runtime error: invalid memory address or nil pointer dereference
> > > > [signal 0xc0000005 code=0x0 addr=0x28 pc=0x290b58]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 报错的
> > > 
> > > 
> > > 原来如此，没有注意到如果resp.Body为空，NewDecoder会返回nil，感谢反馈。
> > 
> > 
> > 还有一点,我说的打开时指的上传文件open,不是之down下来打开,所以这个打开操作应该也需要放到上传主方法里面
> 
> 这个Open没有实现是因为上传的不一定是来自于本地磁盘上的文件，也可能是来自于web框架的一些文件，所以不一定是io.OpenFile。调用者自行Open一下也没有很繁琐，所以就没提供。可以后续考虑单独提供一个UploadFile的api

快修(.......,其实还有一点,那个上传位置能不能设置一个默认值啊.直接传空值又会报错的

**Comment by daofeng2015** [comment]
> > > > > > ```
> > > > > > if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> > > > > > 		return "", err
> > > > > > 	}
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 如果阿里云的api返回的resp里面没有body,就会报错,应该先判断返回状态码再做json处理,还有能把文件打开和文件夹上传也支持了?
> > > > > 
> > > > > 
> > > > > resp.Body如果有问题，Decode也会返回err，就没有细分err的类型了，感觉是无伤大雅哈哈。
> > > > > 文件夹上传的话，对文件夹做个递归遍历，再实现一下阿里云盘的文件夹创建操作 ，就可以了。
> > > > > 文件打开，在我另外一个项目上做了，因为阿里云盘对资源做了referer头的防盗链检查，所以需要加上这个referer头。
> > > > > 这个项目后续想做成webdav形式的，近期在搞teambition网盘的，那个没有做referer头限制，所以近期都会在更新teambition的网盘。这个后续再更新。
> > > > 
> > > > 
> > > > 我是在做上传测试的过程发现的,通过
> > > > ```
> > > > body := strings.NewReader(`{"refresh_token":"` + d.RefreshToken + `"}`)
> > > > 	request, err := http.NewRequestWithContext(ctx, "POST", ApiRefreshToken, body)
> > > > 	if err != nil {
> > > > 		return "", err
> > > > 	}
> > > > 	setRequestHeader(request.Header)
> > > > 	request.Header.Set("content-type", "application/json;charset=UTF-8")
> > > > 	request.Header.Set("accept", "application/json, text/plain, */*")
> > > > 
> > > > 	resp, err := d.httpClient.Do(request)
> > > > 	if resp != nil && resp.Body != nil {
> > > > 		defer resp.Body.Close()
> > > > 	}
> > > > 	if err != nil {
> > > > 		return "", err
> > > > 	}
> > > > 
> > > > 	ret := &struct {
> > > > 		AccessToken    string `json:"access_token"`
> > > > 		ExpiresIn      int64  `json:"expires_in"`
> > > > 		DefaultDriveID string `json:"default_drive_id"`
> > > > 		RefreshToken   string `json:"refresh_token"`
> > > > 	}{}
> > > > 
> > > > 	if err := json.NewDecoder(resp.Body).Decode(ret); err != nil {
> > > > 		return "", err
> > > > 	}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 这里发现的，如果失败就直接
> > > > ```
> > > > 2021/06/28 23:47:52 错误:invalid character '<' looking for beginning of value
> > > > panic: runtime error: invalid memory address or nil pointer dereference
> > > > [signal 0xc0000005 code=0x0 addr=0x28 pc=0x290b58]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 报错的
> > > 
> > > 
> > > 原来如此，没有注意到如果resp.Body为空，NewDecoder会返回nil，感谢反馈。
> > 
> > 
> > 还有一点,我说的打开时指的上传文件open,不是之down下来打开,所以这个打开操作应该也需要放到上传主方法里面
> 
> 这个Open没有实现是因为上传的不一定是来自于本地磁盘上的文件，也可能是来自于web框架的一些文件，所以不一定是io.OpenFile。调用者自行Open一下也没有很繁琐，所以就没提供。可以后续考虑单独提供一个UploadFile的api

快修(.......,其实还有一点,那个上传位置能不能设置一个默认值啊.直接传空值又会报错的
